# Generated by Django 3.1.3 on 2021-05-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0002_auto_20210516_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='platform_slug',
            field=models.CharField(max_length=20),
        ),
    ]
