# Generated by Django 3.2.3 on 2021-05-22 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0004_auto_20210522_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
    ]
