# Generated by Django 3.2.3 on 2021-06-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0007_alter_account_belongs_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='platform',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='platform_slug',
            field=models.CharField(max_length=30),
        ),
    ]
